### ISSUE TITLE
[QT][git]Mockingboard emulation is not working

### ISSUE THREAD

**Issue by FredBezies** [audetto/AppleWin#43] opened 2021-11-07 13:53 UTC
Hello.

I made some tests with QT UI and I noticed that even mockingboard is selected, it is not working. With SDL2 UI, it works perfectly.

My build is based on commit b36c17b

**Comment by audetto** [comment] 2021-11-07 14:33
Will see if the fix is easy, but SDL2 UI + ImGui is really your best choice with better support and settings.

**Comment by audetto** [comment] 2021-11-07 15:31
Works here.
Try to load this `yaml` file: https://github.com/AppleWin/AppleWin-Test/blob/master/v2/OMT-PAL.aws.yaml

It plays for me.
Make sure the volume is not too low.

Does it print anything on console?

Now I remember why I stopped working on it: QT integration on GNOME-Wayland is poor.

Save / restore window positions has strange side effects.
Darg/drop still does not work on GNOME-Wayland.

**Comment by audetto** [comment] 2021-11-07 16:45
OK, that was a bit unfair.
Drag / drop now works and you can drop `yaml` files (will accept floppy and hard disks another day).

And confirmed audio works on Ubuntu and Raspberry.

**Comment by FredBezies** [comment] 2021-11-08 08:23
Using your yaml, then loading the game where sound was broken make it work back. But I do prefer SDL2 version anyway :)

Git version build on an Archlinux.

**Comment by audetto** [comment] 2021-11-08 08:42
Are you sure the correct hardware was configured?
QT and SDL2 use different configuration files. It is possible to use QT's in SDL2 but not the other way round.

**Comment by FredBezies** [comment] 2021-11-08 08:58
> Are you sure the correct hardware was configured? QT and SDL2 use different configuration files. It is possible to use QT's in SDL2 but not the other way round.

Yes, I'm sure. And I use 99% of the time SDL2 port.

**Comment by audetto** [comment] 2023-04-23 15:12
Closing due to lack of evidence.

**Closed by audetto** 2023-04-23 15:12 UTC
Labels: audio
